### PR TITLE
Support for Receivers

### PR DESCRIPTION
**Pull request by datasage**
This PR adds support for receivers to the your library. This may need a bit more testing before its ready to be added. Is there anything you want me to add to this PR before accepting it?

### CODE REVIEW

**Comment by tuurbo** [comment]
Thanks for your work on this. I fixed some code formatting and tweaked a few things. I also did api tests on all the methods and they seem to be working fine.

You can try the dev branch with `composer require tuurbo/spreedly:dev-receivers`

**Comment by datasage** [comment]
My initial tests against a test account seem to be working well for all the main api calls. I plan to do a bit more testing yet.

**Comment by datasage** [comment]
We did more testing on it and as far as I am aware, everything is working fine. Let me know when you merge this into master and release it.

**Comment by datasage** [comment]
I did find a slight error with the update method, was due to an incorrect conversion from XML to JSON format.

**Comment by tuurbo** [comment]
I pushed the fix to dev-receivers. Same fix was also applied to the create method. Also, added more tests.

**Comment by tuurbo** [comment]
Should the deliver method be left as is? Don't completely understand receivers, but I'm assuming the `body` param could be anything, so a string value would probably work best?

**Pull request closed without merging**
