### PR TITLE
Update Guzzle version

### PR DESCRIPTION
**Pull request by adridev**

### CODE REVIEW

**Comment by adridev** [comment]
Not working

**Comment by tuurbo** [comment]
Can't just update to guzzle 6, multiple changes will need to be made to the Client class. I'll look into it, but not sure if i can get it finished soon

**Comment by tuurbo** [comment]
I pushed the changes to the guzzle6 branch. Let me know if it works for you.

 `composer require tuurbo/spreedly:dev-guzzle6`

**Comment by adridev** [comment]
Yes, I have seen that they change Response Class by Psr7 one. I will try to help you with the changes. I will try this branch Thanks!

**Comment by simplenotezy** [comment]
lets merge

**Comment by tuurbo** [comment]
Now available in 1.7.0

**Pull request closed without merging**
